- Changes for Ideas routes and data: Get-Ideas, Update-Idea, Delete-I…
khatri7/cs546-group36-final-project pull request #62
Opened 2022-12-03 03:35 UTC by 1994nikunj

- Almost all Ideas backend changes
- Changes for better code readability

2022-12-03 18:58 UTC, GiriNithin requested changes
Make sure you are using eslint and prettier. Don't change variable names for the sake of changing and also remove comments in all files not required for now.. We can do that 1-2 days before the submission if required. Also, rather than importing entire helpers try to destructure what is required by you.

2022-12-03 18:58 UTC, GiriNithin commented on server/data/ideas.js
> +const helper = require('../utils/ideas');
@1994nikunj Why are you importing the entire helper file.. just destructure the required function and use it.

2022-12-03 18:58 UTC, GiriNithin commented on server/data/ideas.js
> +const { internalServerErr, badRequestErr, notFoundErr } = require('../utils/index');
Are you not using prettier and eslint ??. We are all following eslint and prettier indentation. Make sure you follow the same.

2022-12-03 18:58 UTC, GiriNithin commented on server/data/ideas.js
>  	return createdIdea;
Bro.. what is the point of making createIdeaAcknowledgment into createIdeaAck ??

2022-12-03 18:58 UTC, GiriNithin commented on server/data/ideas.js
> -	} else throw badRequestErr('Idea already liked.');
Same here you are just changing variable names

2022-12-03 18:58 UTC, GiriNithin commented on server/data/ideas.js
> -	} else throw badRequestErr('Idea already unliked.');
Same here

2022-12-03 18:58 UTC, GiriNithin commented on server/routes/ideas.js
>  const { isValidTechnologies } = require('../utils/projects');
Again make sure you are using eslint and prettier

2022-12-03 18:58 UTC, GiriNithin commented on server/routes/ideas.js
> +		const { user } = request;
We are follow req, res as the naming convention

2022-12-03 18:58 UTC, GiriNithin commented on server/routes/ideas.js
>  		} catch (e) {
Same here because of that change in variable name.

2022-12-03 18:58 UTC, GiriNithin commented on server/routes/ideas.js
> +		}
In createIdea you just added comments for each and every single validations and for createComment you did not.. There is no consistency if possible try to remove comments in every file everybody knows what is happening in the code and what they did.

2022-12-03 18:58 UTC, GiriNithin commented on server/routes/ideas.js
> +
Just for the sake of adding comments you could have just changed where it was needed.

2022-12-04 06:28 UTC, khatri7 approved these changes

2022-12-04 06:29 UTC, merged